lincc-frameworks/hyrax

- pyproject.toml
- src/fibad/predict.py
- src/fibad/train.py
- src/fibad_cli/main.py
- src/fibad_cli/predict.py
- src/fibad_cli/train.py
This is meant to be a starting point for the CLI work, and is meant to give us a place to start hanging more code. The next step after this is integrated in my mind is to implement the user configuration file support. 
The current CLI will look something like this: 
```
>>> fibad
usage: fibad [-h] [--version] [{train,predict}] ...
Fibad CLI
positional arguments:
{train,predict}  Verb to execute
args             Arguments for the verb
options:
-h, --help       show this help message and exit
--version        Show version
FIBAD is the Framework for Image-Based Anomaly Detection
```
Getting top level help
```
>>> fibad --help
fibad --help
usage: fibad [-h] [--version] [{train,predict}] ...
Fibad CLI
positional arguments:
{train,predict}  Verb to execute
args             Arguments for the …
```
> CLI scaffolding

- src/fibad/download.py
- src/fibad/downloadCutout/downloadCutout.py
- src/fibad_cli/main.py
- Stats tracking of timing, data size, and bandwidth for cutout transfer
- Ability to specify an arbitrary list of filters to the downloader
- Configurable offset and extent for downloading from a large .fits catalog
- download() helper function codepath now supports kwargs passed from download() -> _download() -> _download_chunk() -> urllib.request.urlopen()
- Timout and chunk size for downloadCutout.py are configurable via this kwargs system.
> Adding bandwith measurement to downloadCutout

- .gitignore
- pyproject.toml
Moving torchvision out of core dependencies in pyproject.toml. Now in an optional dependency section, `examples`. 
Users can install from source with `pip install -e .[dev,examples]`.
Added `data/` to .gitignore so that we don't accidentally commit something in there to the repo.
> Organize pyproject.toml, don't accidentally include `data/` in commit

- src/fibad/download.py
- src/fibad/downloadCutout/downloadCutout.py
Implementation of retry and resume within downloadCutout.py.
Retry means that when a request fails we will try again (defaults to 3 attempts). This is intended to address connection drops and the like. We use configurable exponential backoff to avoid a thundering herd if load from our client is causing some backend failure.
Resume describes the situation where the download fails for unrecoverable reasons (HSC infra goes down) or is terminated (e.g. downloads only occur at night). This generates a resume_download.toml file in the download directory, which allows the exact same download to resume from the chunk that was in progress when the interruption occurred. This resume functionality is off by default to preserve the `download()` interface used by `downloadCutout.py`'s CLI which does …
> Retry and resume functionality for downloader

- src/fibad/download.py
This change is pretty straightforward.
> Setting file names to start with object_id

- src/fibad/download.py
- src/fibad/downloadCutout/downloadCutout.py
- New hook added to downloadCutout._download() to collect failed chunks
- Retries exceeded behavior in downloadCutout._download() altered to default to continuoing the download. If callers of downloadCutout.download() want to stop the download, they can provide a failed_chunk_hook which raises
- Failed chunk collector class keeps failed sky locations and outputs them with astropy.table.Table.write()
- Cleanup documentation of downloadCutout._download and downloadCutout._download_chunk kwargs to also exist at top level in downloadCutout.download() for ease of discoverability.
- Cleanup: convert stats system to a context manager class to avoid proliferation of globals in download.py, and centralize stat pretty printing.
> Skip failed chunks

- src/fibad/download.py
- src/fibad/downloadCutout/downloadCutout.py
- src/fibad/fibad.py
- src/fibad/fibad_default_config.toml
- src/fibad/models/example_cnn_classifier.py
- src/fibad/predict.py
- src/fibad/train.py
- src/fibad_cli/main.py
* Almost all print statements have been changed to logs.
* Logging is initialized in the Fibad object, where the config is parsed
* The logger name is 'fibad' which allows automatic roll-up from other modules within fibad (but not fibad_cli) by simply creating a local logging handle with:
import logging logger = logging.getLogger(__name__)
* This mechanism also works for the downloadCutout code, which has been converted to logging.
* Added documentation to the default config about the log levels and configurable destinations.
> Initial version of logging for fibad.

- src/fibad/download.py
- src/fibad/fibad_default_config.toml
Pretty straightforward addition of these configs with documentation.
> Adding configs for retries, retrywait, timeout, and chunksize

- src/fibad/data_loaders/hsc_data_loader.py
- src/fibad/fibad_default_config.toml
- src/fibad/models/example_autoencoder.py
- tests/fibad/test_hsc_dataset.py
NOTE: This PR is based on https://github.com/lincc-frameworks/fibad/pull/33 If you are reviewing review that one first.
Once PR 33 is merged the diff view on this will get much easier. For now look at the last commit's diff only (https://github.com/lincc-frameworks/fibad/pull/49/commits/bc75191630fb1b3608be2145c760eef97928b226)
- Objects who have any cutouts not capable of providing enough pixels are pruned
- data_loader:crop_to is the config where pixel values are specified
- Not providing the config gives you the old auto-detect behavior where the
largest size that will work for all images in the data path is chosen.
> Adding user-specified cutout crop size. 

- src/fibad/config_utils.py
- src/fibad/fibad_default_config.toml
- Also make it easier to run fibad commands by using ./fibad_config.toml as the user-supplied config in situations where no config is specified explicitly
An example config you will probably need after this change merges looks something like:
```
[download]
username = "mtauraso@local"
password = "cCw+nX53lmNLHMy+JbizpH/dl4t7sxljiNm6a7k1"
fits_file = "../hscplay/temp.fits"
cutout_dir = "../hscplay/cutouts/"
[data_loader]
name = "HSCDataLoader"
path = "../hscplay/cutouts"
```
For downloader and data loader.
If this merges I'm planning to reset my HSC password shortly thereafter in order to avoid the current situation where our pubic repo has live credentials to their system.
> Remove Michael's password from default config file

- src/fibad/download.py
- src/fibad/downloadCutout/downloadCutout.py
- src/fibad/fibad.py
- src/fibad/fibad_default_config.toml
- Support for multiple connections via 'concurrent_connections' config
- Replaced FailedChunkCollector and old resume system in downloadCutout.py with manifest-based resume system
- Added __hash__ and __eq__ to downloadCutout Rects so they can be dictionary keys
- Pulled downloader functions into a class so class constants could be namespaced
> Multithreaded manifest-based downloader

- src/fibad/download.py
- src/fibad/download_stats.py
- Stats have their own thread for printing at a configurable cadence
- There are 1 hr trailing window and cumulative stats
- File rate is now reported as files/24h
- Stats live in a separate file from the downloader
- Stats code is (hopefully) easier to read
> Proper multithreaded stats

- src/fibad/download.py
- src/fibad/downloadCutout/downloadCutout.py
- src/fibad/fibad_default_config.toml
- Added configs so image/variance/mask layer downloads can be configured.
- Put filter lower in the sort order for dC.Rect so that duplicate dowloading in a resume situation is minimized for large downloads.
- Concurrent connection error is now correct to our understanding of HSC's server-side behavior.
> Various Fixups for klone download

- example_notebooks/GettingStartedDownloader.ipynb
- pyproject.toml
- src/fibad/download.py
- src/fibad/downloadCutout/downloadCutout.py
- src/fibad/fibad.py
- Rects in downloadCutout.py now track dimension of the file
- Downloader now is a proper object and holds more of its rect bookkeeping as instance state.
- Downloader creation is lightweight, and most work is still in .run()
- Example downloader notebook has been updated to use the new interface to generate histograms of downloaded data.
> Add a fibad top-level method to get the dimensions of downloaded files

- src/fibad/config_utils.py
- src/fibad/data_loaders/data_loader_registry.py
- src/fibad/data_loaders/example_cifar_data_loader.py
- src/fibad/data_loaders/hsc_data_loader.py
- src/fibad/download.py
- src/fibad/fibad.py
- src/fibad/fibad_default_config.toml
- src/fibad/models/example_autoencoder.py
- src/fibad/models/example_cnn_classifier.py
- src/fibad/models/model_registry.py
- src/fibad/plugin_utils.py
- src/fibad/train.py
- All configuration dicts are now ConfigDict. A ConfigDict is a version of dict that raises RuntimeError quite a lot when you try to mutate it or when you access values that weren't set at construction time.
- There is a new validate step for runtime config that ensures every config key that appears at runtime has a default defined in fibad_default_config.toml.
- Usages of .get() on config dictionaries have been removed, so all defaults now live in fibad_default_config.toml. Config access is entirely via __getitem__ / [].
- The sum total of the above means that we expect any new config which is missing a default value to generate a runtime error as early as possible if it is referenced anywhere in code, or in a user-supplied configuration.
- Several config values have changed …
> Centralize config defaults, add safety for Config updates

- src/fibad/data_sets/hsc_data_set.py
- src/fibad/fibad_default_config.toml
- src/fibad/pytorch_ignite.py
- tests/fibad/test_hsc_dataset.py
Moving `filter` and `crop_to` to the `[data_set]` table in the default config to make defining the dataloader easier.
Now the pytorch ignite dataloader can be defined with **kwargs instead of a bunch of hardcoded config parameters.
> Move config parameters to a different table so that we can define a dataloader easier

- src/fibad/download.py
This is a breaking change for the manifest file format, in that downloads started before this change will not be able to resume if resumed using a version of fibad after this change.
Prior to this change If you have a config that downloads mask or variance, resume would simply fail (issue #98)
The cause was that the image, variance, and mask rect parameters weren't saved to the manifest file, so on resume _prune_downloaded_rects() could not match the  manifest with the rects generated from the catalog.
In this case the rects generated from the catalog had config-provided values for image, mask and variance. The rects generated from reading the manifest had the dc.Rect default values of image=True, mask=False and variance=False.
This change ensures that all the dc.Rect immutable fields, …
> Include all immutable dc.Rect fields in manifest so Resume works in all configs.

- src/fibad/__init__.py
- src/fibad/config_utils.py
- src/fibad/fibad.py
- tests/fibad/test_config_utils.py
Adding a ConfigManager class to help wrangle the various defaults that could be imported.
The approach we're implementing is the following.
* Load the fibad_default_config
* Load the user_specific_config (USC), if defined
* Scan the USC for any external libraries, they look like lib specs under the `name` keys. i.e. `"module.submod.class"`
* Collect the file paths to default config files that are defined in the external libraries. For now, we assume the files are called `default_config.toml`.
* Merge all the external default configs to create a merged-external-default-config
* Merge the fibad default and the merged-external default configs to create a total-default-config
* Merge the USC into the total-default-config
* Validate the USC against the total-default-config
There's lots of …
> Handle externally defined default configuration files 

- src/fibad/data_sets/example_cifar_data_set.py
- src/fibad/data_sets/hsc_data_set.py
- src/fibad/fibad_default_config.toml
- src/fibad/predict.py
- src/fibad/pytorch_ignite.py
- src/fibad/train.py
- tests/fibad/test_hsc_dataset.py
- HSCDataSet has been significantly modified to implement splits
- Constructors for fibad_data_sets now take a split argument
- Tests pass, but new functionality not yet tested
- New configs added in new "prepare" section to define splits
- Some configs in "model" reorganized to a "train" section that is similar to the "prepare" "predict" and "download" sections in that it configures the action more than anything else.
- Added "split" config to train and predict sections to select the split that will be used.
> Splits for HSCDataSet

- src/fibad/config_utils.py
- src/fibad/fibad_default_config.toml
- tests/fibad/test_config_utils.py
- tests/fibad/test_data/test_default_config.toml
- tests/fibad/test_data/test_user_config.toml
The primary purpose of this PR is to add a `dev_mode` flag that will allow developers (specifically of external libraries) to move more quickly, and avoid having to define default config values. Instead they will be able to modify and use their user-specific config file during development, with the understanding that, prior to deploying/releasing their code, they will need to introduce a default config file.
Additionally, this PR removes the unused "use_gpu" default config key.
> Adding `dev_mode = false` to `fibad_default_config.toml`

- src/fibad/data_sets/hsc_data_set.py
- src/fibad/downloadCutout/downloadCutout.py
- src/fibad/fibad.py
- src/fibad/fibad_default_config.toml
- src/fibad/prepare.py
- tests/fibad/test_hsc_dataset.py
- We can take a fits file as a config
- We filter objects_ids out of a big dataset based on it
- We also skip filesystem checks if there is enough info in the filter catalog.
- Lacks any unit testing
- Added the prepare verb, but right now it just gives you the dataset object when run from a notebook.
Closes #111
> Initial version of filter_catalog feature.

- pyproject.toml
- src/fibad/config_utils.py
- src/fibad/data_sets/hsc_data_set.py
- src/fibad/download.py
- src/fibad/fibad.py
- src/fibad/rebuild_manifest.py
- tests/fibad/test_hsc_dataset.py
- Added a new verb rebuild_manifest
- When run with the HSC dataset class this verb will: 0) Scan the data directory and ingest HSC cutout files 1) Read in the original catalog file configured for download for metadata 2) Write out rebuilt_manifest.fits in the data directory
- Fixed up config resolution so that fibad_config.toml in the cwd works again for CLI invocations.
- File scanning has been parallelized with multiprocessing to reduce time from ~30d -> 6hr on hyak w 24M files
- Number of processes to launch dynamically chosen based on system limits, with intent to achieve max io bandwidth.
> Rebuild a fits manifest from an HSC data directory.

- src/fibad/data_sets/hsc_data_set.py
The print statement somehow made it's way into main. it was causing I/O rate to exceed in Jupyter.
> Removing dimensions print statement

- src/fibad/fibad_default_config.toml
- src/fibad/models/example_cnn_classifier.py
- src/fibad/models/model_registry.py
- src/fibad/plugin_utils.py
This is an initial implementation that allows defining PyTorch Loss (Criterion) and Optimizers from within the config file. 
Two new tables are introduced, `[criterion]` and `[optimizer]` and we currently use the relatively familiar libpath approach to avoid having to create a registry of pytorch criterion and optimizer functions which would need to be loaded at run time (kind of heavy and slow) 
The keys in the tables need to share the same names as the parameters that would be passed to the loss or optimizer functions. (we just use  `**config` to pass the params in). 
Within the `__init__` function of either the built in models or in an external class the user will still need to call: 
```
self.optimizer = self._optimizer()
self.criterion = self._criterion()
```
(I would like to fix …
> Allow definition of Loss and Optimizer in config file.

- src/fibad/data_sets/hsc_data_set.py
- src/fibad/download.py
- Should fix issue #127.
- Moved removal of incomplete downloads from the prune stage to the f/s read stage
- Added a better error to the case where HSCDataSet arrives at an absurdly small size of image to crop to.
- Unrelated fix to downloader to make it respect concurrent_connections.
> Adding guards in HSCDataSet for the manifest representation of un-downloaded files

- src/fibad/predict.py
- src/fibad/prepare.py
- src/fibad/pytorch_ignite.py
- src/fibad/rebuild_manifest.py
- src/fibad/train.py
Breaking these apart avoids unnecessary creation of model instances in prepare and rebuild_manifest. And this opens the door for a potentially more intuitive way to create datasets for training that include (train, [validate, test]) subsets. 
This PR only implements the separation of the `setup_model_and_dataset` function and percolates that change down to the various fibad verb implementations.
> Breaking `setup_model_and_dataset` into two functions.

- docs/notebooks/train_model.ipynb
- src/fibad/data_sets/example_cifar_data_set.py
- src/fibad/fibad_default_config.toml
- src/fibad/infer.py
- src/fibad/models/example_autoencoder.py
- src/fibad/models/example_cnn_classifier.py
- src/fibad/models/example_hsc_autoencoder.py
- src/fibad/models/model_registry.py
- src/fibad/pytorch_ignite.py
Remove `batch_size` from `infer` table. Fixes #145.
CiFAR example dataset wasn't working correctly for inference - changed the behavior of splits. Fixes #144
Remove need to explicitly define criterion and optimizer for models. Users still have the option to do so, but it's not required. Fixes #134
> Fix assorted issues encountered while experimenting with vectordb

- src/fibad/data_sets/hsc_data_set.py
This PR is more of a question for the group about what the semantic meaning of setting a config to False is.
Consider this user config:
```
[data_set]
validate_size=false
```
Our existing code for generating validate splits had a bug, where it would generate you a validation split so long as train_size+test_size < 0.5. This is weird behavior and probably a result of not telling `np.round` how many decimal points to round to.
**Under this config do we construct and ultimately use a validation split or not?**
~~The code in this PR says "yes", but I'm not sure if that's correct.
At the moment "no" would mean removing the `if` block in `hsc_data_set.py` and leaving the test unchanged.
Thoughts?~~
We decided its that the answer is "no" to the question above. It is valid to not have a …
> Is having no validation split valid?

- src/fibad/fibad_default_config.toml
See discussion on Issue #138 This implements @drewoldag 's suggestion.
> Default to using the whole dataset for inference unless overriden

- .gitignore
- src/fibad/download.py
- src/fibad/fibad_default_config.toml
Simple support for a credentials.ini file with documentation
> Adding credentials file support

- pyproject.toml
- src/fibad/config_utils.py
- src/fibad/fibad_default_config.toml
- tests/fibad/test_config_utils.py
- tests/fibad/test_data/test_default_config.toml
- tests/fibad/test_data/test_user_config.toml
Doing my best to apply some uniform formatting to the config file to make it a little less overwhelming. 
The linting rules that I tried to adhere to:
1. No table-level comments
2. No comments outside of a table
3. Two lines between tables
4. One line between a key and the following comment
5. 2 lines of comments "maximum" per key - I failed on this for the test/validation/train splits.
6. No free floating blocks of comments - Again I failed when it came to the test/validation/train splits, there's just a lot there.
7. Reasonable maximum line length for comments
8. Include optional values when possible (i.e. allowed log levels)
9. Tried to have one comment per key, but used best judgement there. (i.e. username, password only got one comment)
> Cleaning up default config formatting, values and comments

- src/fibad/config_utils.py
- src/fibad/fibad_default_config.toml
- src/fibad/models/model_registry.py
This PR allows defining subtables in the config that will sandbox the parameters used for a particular criterion or optimizer. 
This means that parameters for multiple functions can be included in the config without conflicting with each other - the biggest risk is that different functions might have parameters with the same name, but substantially different meanings.
> Optimizer and criterion subtables

- src/fibad/data_sets/hsc_data_set.py
- src/fibad/fibad_default_config.toml
- tests/fibad/test_hsc_dataset.py
Previously, the HSC DataSet class did a tanh transformation before feeding data into models.
This PR:-
- adds the option for the user to specify transformations or skip transformations altogether
- adds the capability for any `numpy` function to be used as a transform.
- [X ] My PR includes a link to the issue that I am addressing
- This PR addresses https://github.com/lincc-frameworks/fibad/issues/160
- I introduced a new function, `_get_np_function` in `HSCDataSetContainer` that maps passed strings to `numpy` functions
- I also added a few tests to check different scenarios
> Adding the Capability for any numpy function to be passed as a transform variable

- pyproject.toml
- src/fibad/fibad_default_config.toml
- src/fibad/pytorch_ignite.py
- src/fibad/train.py
If testing locally be sure to `pip install mlflow`, and optionally `pynvml` if you want to collect gpu metrics.
You should be able to log model parameters and metrics immediately without any initial setup. To view the results you'll need to start the mlflow server using the following at the command line: 
`mlflow ui --backend-store-uri file://<.../results/mlflow>` 
Pass in the full path to the directory `/<where your results are>/results/mlflow` with a leading `/`. 
Then go to `http://127.0.0.1:5000 and you should be presented with the MLFlow UI. 
The default experiment is `notebook`. You can change the experiment name in your config using:
```
[train]
experiment_name = "fav_experiment_name"
```
In this example, I used port 8080 by starting mlflow server like so: `mlflow ui …
> WIP Initial commit to get some things logged to mlflow.

- src/fibad/train.py
Actually makes use of the `experiment_name` in the config file. Note that we need to cast this to a `str(...)` in order for `mlflow.set_experiment` to work correctly. 
If this is blocking, don't wait for me to merge this change.
> Using experiment_name from config to set mlflow experiment name.

- src/fibad/data_sets/hsc_data_set.py
- src/fibad/infer.py
Copied the structure of `shape(self)`.
> Pass along the HSCDataset id for populating vectordb

- src/fibad/config_utils.py
- src/fibad/plugin_utils.py
This seems to address the issue that was raised in issue #108. Still not immediately clear why this is sometimes an issue, but it seems to be.
> Being more explicit with the import of importlib.util.

- src/fibad/verbs/umap.py
Adding default value for `input_dir`, so that umap will default to the most recent `infer` directory, if one is not specified.
> Add default of `None` to `umap` verb

- src/fibad/data_sets/example_cifar_data_set.py
This PR amounted to duplicating a lot of code that was in hsc dataset. 
The protection and approach is broadly applicable, so it probably makes sense to abstract this up a level and inject the code when a dataset class uses the @fibad_dataset decorator. 
The only reason I didn't take that step here was because I want to take a minute to think clearly about how this will work as we expand beyond just Pytorch data sets. A little research into the HuggingFace dataset API would be good.
> Protect against 0-length validation splits in cifar dataset

- src/fibad/config_utils.py
- src/fibad/fibad.py
- tests/fibad/test_config_utils.py
- tests/fibad/test_data/test_user_config_repeated_keys.toml
Implementing simple function to print specific config tables. The goal is to allow a user to call `fibad_instance.config.help(...)` and get see the configuration comments printed. 
It's unintuitive how to parse through the data structure that tomlkit maintains in order to print out just the comments surrounding the key of interest. So as a half set, we can just print the entire enclosing table. 
So for instance:
```
import fibad
f = fibad.Fibad()
f.config.help('general', 'dev_mode')
```
Prints the full `[general]` table:
```
[general]
dev_mode = false
log_destination = "stderr"
log_level = "info"
data_dir = "./data"
#Top level directory for writing results.
results_dir = "./results"
```
Usage for the help looks like this:
```
f = fibad.Fibad()
f.config.help()  # Pretty prints the entire …
```
> Configuration help in notebook

- src/fibad/fibad_default_config.toml
- src/fibad/train.py
This PR introduces a new config value, `['train']['run_name']`. The default value is `false`. 
When this value is false and the user runs `fibad.train()`, the resulting MLFlow run will be the same as the auto-generated results directory, i.e. `<timestamp>-train-<uid>`. 
When the user provides a value with a string representation, i.e. "super_turtle", that value will be used as the MLFlow run name.
In the screenshot below the first in the list is user defined, the second in the list is the default timestamped value. The third item in the list is a previously autogenerated run name.
> Allow user to specify MLFlow run name via the config.

- src/fibad/data_sets/inference_dataset.py
We should only merge this once we're sure we don't need this codepath anymore.
i.e. all inference results we care about ought have a batch index file.
> Removing create_index codepath

- docs/pre_executed/visualize.ipynb
- src/fibad/data_sets/example_cifar_data_set.py
- src/fibad/data_sets/hsc_data_set.py
- src/fibad/data_sets/inference_dataset.py
- src/fibad/pytorch_ignite.py
- src/fibad/rebuild_manifest.py
- src/fibad/train.py
- src/fibad/verbs/lookup.py
- src/fibad/verbs/umap.py
- src/fibad/verbs/visualize.py
- tests/fibad/test_hsc_dataset.py
- tests/fibad/test_splits.py
- Data Sets no longer have any awareness of splits
- All splitting behavior is negotiated between the verb and pytorch_ignite while creating distributed data loader(s).
- HSCDataSetSplit and HSCDataSetContainer are removed entirely, with HSCDataSet now having the code that was in HSCDataSetContainer.
- CifarDataSet is much shorter and only uses the training CIFAR dataset
- Tests of splits are in their own file and preserve behavior with prior HSCDataSetSplit tests.
> Extracting dataset split code from data_sets

- .gitignore
- pyproject.toml
- src/fibad/fibad_default_config.toml
- src/fibad/model_exporters.py
- src/fibad/train.py
- tests/fibad/test_hsc_dataset.py
- tests/fibad/test_splits.py
This PR is an first step toward exporting multiple forms of models. Obviously at this point we're only focusing on PyTorch, but I've tried to write this in a way that will support future different ML frameworks. I probably haven't done this in an ideal way, but it's a start. Two aspects of this are worth noting, and I would appreciate feedback on them.
I've created a simple dictionary that carries "context" from the train.run function into the export_to_onnx function. This context object sounds a lot like a python `dataclass`. Additionally, it feels like a reasonable way to percolate information back up to the fibad object after `train` has finished. Extra-additionally, perhaps this is the right time to transform `train` into a proper verb class.
In the `model_exporters` module, the …
> Initial investigation of exporting to ONNX after training.

- .pre-commit-config.yaml
Adding `_build` to the list of excluded directories when pre-commit builds documentation.
> Prevent recursive `_build` directories in docs

- src/fibad/data_sets/inference_dataset.py
- src/fibad/verbs/umap.py
- We use a process pool to do the transform
- We use another process pool to do writing of inference data out (also impacts infer verb)
- Some of the loudest warnings from the umap package have been supressed
> Parallelize umap with process pools

- pyproject.toml
Context on the issue:
https://github.com/anderskm/gputil/issues/59
https://github.com/anderskm/gputil/pull/60
GPUtil library has not released since 2018, so we may need to rely on this branch for some time.
> Workaround for CI

- src/fibad/fibad_default_config.toml
- src/fibad/infer.py
- src/fibad/vector_dbs/chromadb_impl.py
- src/fibad/vector_dbs/vector_db_factory.py
- src/fibad/vector_dbs/vector_db_interface.py
Implementing sharding for the chromadb vector database because we have seen that the insertion times become overly burdensome as total size of the "collection" (database table) becomes large, by some definition of large. 
Sharding helps keep the insertion costs down with the downstream cost of less efficient nearest neighbor look ups. Now we must scan all the shards for nearest neighbors instead of just scanning a single collection.
> Initial vectordb interface and chromadb impl with sharding

- .setup_dev.sh
- src/fibad/data_sets/hsc_data_set.py
- tests/fibad/test_hsc_dataset.py
- When manifest or filter_catalog files contain filenames that are obviously for the wrong object ID, we will drop the relevant object and emit a warning
- Testing system extended to allow tests for malformed manifests to be written.
- Small fixup to .setup_dev.sh script to make sure that it's promise to "not output logs" unless there is an error is actually true.
> Add a check for malformed manifest files

- docs/pre_executed/mpr_demo.ipynb
- src/fibad/data_sets/hsc_data_set.py
- src/fibad/fibad_default_config.toml
- src/fibad/train.py
- tests/fibad/test_hsc_dataset.py
This spawns a pre-cache thread during HSCDataSet initialization. The pre-cache thread starts many worker threads that read in all the dataset files to the tensor cache. The idea is to confront a latency-limited network storage backend with a large number of requests all at once, such that we will receive the files in memory at the greatest overall bandwidth.
This change also logs a `HSCDataSet/preload_1k_obj_s` metric to tensorboard which should give an idea of object bandwidth. It is the elapsed time to load 1000 objects measured every 1000 objects.
The change is protected under a config `config["data_set"]["preload_cache"]` The config is on by default (similar to `use_cache`) because it should be harmless for small datasets and laptop usage.
> First implementation of cache warming for HSCDataSet

- src/hyrax/data_sets/__init__.py
- src/hyrax/data_sets/data_set_registry.py
- src/hyrax/data_sets/hsc_data_set.py
- src/hyrax/data_sets/hyrax_cifar_data_set.py
- src/hyrax/data_sets/inference_dataset.py
This is a skeleton of a superclass for Datasets. The intent is to provide a scaffold for folks writing dataset classes such that they have:
1) Clear instructions on what functions to implement
2) "Batteries included" for the more complex features of Dataset classes that HSC relies on (metadata, original_config, etc)
The version below is a noop change to fibad's functionality, and the individual abstract methods are commented with how they would be implemented in the base class to make future dataset classes easier to write.
I'm looking for feedback on the overall interface at this point, since this code doesn't do anything at the moment 🙂
> Initial dataset class interface

- src/hyrax/config_utils.py
- src/hyrax/data_sets/__init__.py
- src/hyrax/data_sets/data_set_registry.py
- src/hyrax/data_sets/hsc_data_set.py
- src/hyrax/data_sets/hyrax_cifar_data_set.py
- src/hyrax/data_sets/inference_dataset.py
- src/hyrax/pytorch_ignite.py
- Configuration subsystem now handles path resolution for a list of config keys. Hardcoded for now, but we can add as external library config interface takes shape.
- original_config removed from base class interface. Logic can live exclusively in InferenceDataset/InferenceDatasetWriter with the config subsystem handling path resolution
- Default implementation of ids() and shape() in base class
- s/Dataset/HyraxDataset to avoid clashing with torch
> Move Dataset code into base classes pt1

- pyproject.toml
- src/hyrax/gpu_monitor.py
GPUtil has been stagnant for several years now, and recently broke. The metrics that it provides are useful, but not so useful that we should incur the penalty of not being able to deploy to pypi by taking a dependency on a github branch. 
In this PR I have:
- Removed the dependency on GPUtil.
- Copied over the relevant code from GPUtil
- Trimmed down the call to nvidia-smi to be only what is needed by Hyrax
- Converted the `GPU` class into a dataclass.
> Remove dependency on GPUtil

- .pre-commit-config.yaml
- docs/pre_executed/visualize.ipynb
- src/hyrax/data_sets/data_set_registry.py
- src/hyrax/data_sets/hsc_data_set.py
- src/hyrax/data_sets/hyrax_cifar_data_set.py
- src/hyrax/data_sets/inference_dataset.py
- src/hyrax/models/hyrax_autoencoder.py
- Metadata accessors `metadata()` and `metadata_fields()` moved to HyraxDataset base class
- HSCDataset and HyraxCifarDataset modified to use the new interface
- HyraxDataset constructor optionally takes a metadata_table for subclasses that want to opt in to metadata
Sidebar:
- Added a precommit hook which looks for 'xcxc'/'XCXC' across all source files. This is a string you can use in a note-to-self or work-in-progress comment which will flag to you so you don't forget to handle it before checking in.
> Move dataset code into base class pt 2: Metadata edition

- src/hyrax/data_sets/data_set_registry.py
Adding some logic to check for tuples returned from dataset __getitem__ or __iter__.
Not sure if this is the best long term solution or not, but this fix keeps the existing example notebooks running for the time being.
> Add logic so that CiFAR dataset works out of the box

- src/hyrax/data_sets/inference_dataset.py
Fix to the issue @drewoldag and @mi-dai ran into with string ids of variable length during inference.
> Fixing InferenceDatasetWriter id type for strings of variable length

- src/hyrax/vector_dbs/chromadb_impl.py
Fixes #272 which was introduced by an [upstream API change in chromadb](https://github.com/chroma-core/chroma/commit/e36511bc8c8d4802ed1679b890dd19e613da9524#diff-0dabdf3b1a34381fc025f4a2a8b8225d84188dfbf8f102f4e7c3f1c08b5c9af3L315-R328) which removed `IncludeEnum.embeddings` in favor of `Literal['embeddings']` in their type definitions.
> Fix for upstream API change to chromadb

- docs/pre_executed/mpr_demo.ipynb
- docs/pre_executed/mpr_demo_plotting.py
- src/hyrax/config_utils.py
- src/hyrax/data_sets/hsc_data_set.py
- src/hyrax/download.py
- src/hyrax/pytorch_ignite.py
- src/hyrax/train.py
Fixes #271 
Basic issue is that in pathlib `.resolve()` and `.absolute()` don't expand `~` but `.expanduser()` does without doing any additional path changes. 
Everywhere where we have written `.resolve()` in library code has been changed to `.expanduser().resolve()` which produces correct behavior on valid user paths.
> Allow user paths (unix ~) in config values

- docs/external_libraries.rst
- pyproject.toml
- src/hyrax/data_sets/__init__.py
- src/hyrax/data_sets/data_set_registry.py
- src/hyrax/data_sets/hsc_data_set.py
- src/hyrax/data_sets/hyrax_cifar_data_set.py
- src/hyrax/infer.py
- src/hyrax/pytorch_ignite.py
- tests/hyrax/test_e2e.py
- Adds an example CIFAR iterable dataset
- Changes to pytorch_ignite.py to work around an ignite bug in iterable datasets https://github.com/pytorch/ignite/issues/3372
- New is_iterable() and is_map() interface on dataset base class to unify discernment logic
- Support for abstract base classes that derive from HyraxDataset not being themselves checked for required methods.
> Iterable dataset support

- src/hyrax/verbs/umap.py
Closes https://github.com/lincc-frameworks/hyrax/issues/290
When `config_sample_size = False`, `sample_size` used to be a float before. Casting it as an `int` now to solve this bug
Closes https://github.com/lincc-frameworks/hyrax/issues/291
While using multiprocessing, we now use the 'spawn' context to safely create subprocesses after
OpenMP threads have been initialized by any other previous step (e.g., data loader)
> Umap bugfixes

- src/hyrax/hyrax_default_config.toml
- src/hyrax/verbs/umap.py
Creates a `config["umap"]["reduce_memory_usage"]` flag that users can use to run the `umap` process only as a single-threaded operation, along with Python garbage collection and other memory-saving behaviour.
`["umap"]["reduce_memory_usage"]` is set to `False` by default, which replicates previous behaviour.  
To give a scale of numbers:- 
- with the flag set to `True`; 100k infer points can be fitted by a umap with ~250GBs of RAM
- Without the flag, this requirement balloons to more than 500GB
> Reducing umap memory footprint

- docs/pre_executed/mpr_demo.ipynb
- docs/pre_executed/visualize.ipynb
- src/hyrax/data_sets/data_set_registry.py
- src/hyrax/hyrax_default_config.toml
- src/hyrax/verbs/infer.py
- src/hyrax/verbs/visualize.py
- tests/hyrax/test_e2e.py
- tests/hyrax/test_hsc_dataset.py
- Getting started steps should work now out of the box
- You now must set config['visualize']['fields'] to a list of the metadata fields you'd like the visualizer to use
- End to end tests now also test the visualizer
- Classes deriving from HyraxDataset who do not specify an "object_id" column in their metadata will now have that column pre-filled with the contents of their .ids() member.
- Minor changes to HSCDataSet tests to enable end-to-end testing since metadata is normally disabled on HSCDataSet for unit testing
Closes #282
> Adding column config to visualizer

- src/hyrax/data_sets/data_set_registry.py
- src/hyrax/data_sets/hyrax_cifar_data_set.py
- src/hyrax/data_sets/inference_dataset.py
- src/hyrax/models/hyrax_autoencoder.py
- src/hyrax/models/model_registry.py
- src/hyrax/pytorch_ignite.py
- src/hyrax/train.py
- src/hyrax/verbs/infer.py
- HyraxCifarDataSet is converted as an example
- Changes to Hyrax are backwards compatible to datasets returning Tensors or tuples of tensors directly.
- Models can now write a to_tensor() static method which converts a dict from whatever dataset to an approprite tensor.
- Torch's batching unifies the first level of dictionary keys so batches are now of type dict with tensor-y values representing the entirety of the batch for each top level dict key. (This is less a change and more just what torch does. We now rely on it)
- Dataset classes now no longer must define a shape() method. the backend simply pulls a sample element and determines the shape when needed. This operation unfortunately now requires both a model and a dataset, but it does not occur very often in code.
> Adding support for dict-based datasets.

- docs/pre_executed/hyrax_hats_cutouts.ipynb
- src/hyrax/data_sets/lsst_dataset.py
LSST Dataset uses a LSDB/Hats catalog to create cutouts.
- LSSTDataset can be configured to use a hats catalog
- An example of preparing and using a hats catalog is in docs/pre_executed/hyrax_hats_cutouts.ipynb
- LSSTDataset now accepts butler, skymap, and sw/sh dimensions for cutouts as config.
> LSST Dataset uses a LSDB/Hats catalog to create cutouts.

- src/hyrax/verbs/vdb_index.py
This change fixes a bug that was causing the ids and vectors to lose association.
> Fix bug in `index` that dissociates id and vector when inserting

- src/hyrax/data_sets/inference_dataset.py
Save an "insert-sorted" batch index file alongside the current "id-sorted" batch index.
This will live alongside the current "batch_index.npy" for a while. Down the line, if/when we discover that having the index available in insert order is valuable, we'll have it, and we won't have to bother users to rerun their inference.
> Save insert-sorted in addition to id-sorted InferenceDataSet batch index files

- .pre-commit-config.yaml
- pyproject.toml
- src/hyrax/verbs/umap.py
- tests/hyrax/conftest.py
- tests/hyrax/test_infer.py
- tests/hyrax/test_train.py
- tests/hyrax/test_umap.py
- tests/hyrax/test_vdb_index.py
- Added pytest-xdist to our standard pre-commit. shaves ~6s off a pytest run. After pip installing dev dependencies, run 'pytest -n auto -m "not slow"' to run parallelized.
- Added a Umap ordering/data identity test
- Factored more of our fixtures for infer/index/umap tests into conftest.py
> Add umap ordering tests and use pytest-xdist

- docs/notebooks.rst
- docs/pre_executed/vector_db_demo.ipynb
- src/hyrax/config_utils.py
- src/hyrax/vector_dbs/chromadb_impl.py
- src/hyrax/verbs/__init__.py
- src/hyrax/verbs/database_connection.py
- src/hyrax/verbs/save_to_database.py
- tests/hyrax/test_chromadb_impl.py
- tests/hyrax/test_save_to_database.py
- Cleaning up vector database UX.
- Now it's `h.save_to_database()` instead of `h.index()`.
- Connect to database without needing to know the database type with `h.database_connection`.
- Ensure that a user cannot insert duplicate ids into chromadb.
- Added `database_connection` verb
- Renamed `index` to `save_to_database`
- Created a new example notebook.
- Updated tests
- Modified ConfigManager - made the private static method, `read_runtime_config` public so that we can quickly read a config from a result directory without having to invoke the entire ConfigManager machinery (which is really slow now :()
> Polishing the vector db user experience

- src/hyrax/data_sets/inference_dataset.py
Just read the config in the results directory instead of hydrating the entire config.
Probably not a huge time savings, but I don't think it's necessary to rehydrate the config file from scratch in this case, since I believe all we want to do is use some values from it to properly instantiate the dataset.
> Read the original config file from results directory for InferenceDataset

- docs/external_libraries.rst
- src/hyrax/hyrax_default_config.toml
- src/hyrax/pytorch_ignite.py
- src/hyrax/verbs/infer.py
- tests/hyrax/test_nan.py
This is our first run at image based handling of NaN values.
The basic algorithm is that it looks at every image in the batch and replaces NaNs in the image with the 5th percentile value from that same image. The percentile is configurable, and we can add other methods over time.
This is intended as a precursor to having LSST visit images as inputs to hyrax models, but could be immediately usable by anyone with NaNs in their data.
> Basic NaN handling using a quantile-based system

- docs/pre_executed/hyrax_hats_cutouts.ipynb
- src/hyrax/data_sets/__init__.py
- src/hyrax/data_sets/downloaded_lsst_dataset.py
- src/hyrax/data_sets/lsst_dataset.py
- src/hyrax/hyrax_default_config.toml
1. LSSTDataset: Updates the LSSTDataset to add support for Astropy Tables (i.e., any file format that is supported by `astropy`) 
2. Updates the demo notebook to show the above feature
3. Introduces a new dataset called `DownloadedLSSTDataset` that inherits from `LSSTDataset`
- This dataset downloads tensors and saves them as `.pt` files for rapid access
- Uses the same LRU caching strategy as LSSTDataset; but multi-threads it 
- Creates and updates a manifest file during download, similar to `HSCDataset` 
- Provides some convenience functions to monitor / help during donwload. 
Notes:- 
- Tested that this works on the RSP
- @mtauraso & @drewoldag : If either you think this code will benefit from refactoring or other major structural changes; please feel free to push directly to this …
> New Features for LSST X Hyrax

- src/hyrax/pytorch_ignite.py
- src/hyrax/verbs/save_to_database.py
- tests/hyrax/conftest.py
- tests/hyrax/test_infer.py
- tests/hyrax/test_inference_dataset.py
- tests/hyrax/test_nan.py
- tests/hyrax/test_save_to_database.py
- tests/hyrax/test_umap.py
Flattening vectors before inserting into vector db, checking if batch is tuple before de-NaN-ifying.
- The verb `save_to_database` was not flattening the vectors before attempting to insert them into the database, now it does.
- Additionally, in the `_handle_nan` function, if a batch is provided that is a tuple, the `torch.any(torch.isnan(batch))` logic would fail, complaining that the batch wasn't a tensor. I added a little type check-and-convert with the assumption that getting to a working solution is better for now, even if it's not the idealized solution.
> Flatten vectors and check for tuples

- src/hyrax/pytorch_ignite.py
- tests/hyrax/conftest.py
- tests/hyrax/test_nan.py
Implementing single dispatch for nan-handling. Might be over doing it but it makes nice separation. Added and updated tests.
The root cause was that I was overriding the value of `batch` with `batch[0]` when the input type of `batch` was a tuple. Thus, when batch was returned, it had lost all the other elements of the tuple. 
This is fixed now. The singledispatch approach allows slightly cleaner treatment of logic necessary. This is mostly to address the case of recombining the values from `_handle_nan_quantile` and any future nan handling approaches taken. Really I just didn't want to have piles of `if isinstance(batch, tuple)` all over the place. 
Also added a test to make sure this is working as expected for our dataset types, and updated the HyraxLoopback model to handle tuples …
> Fixing bug in `_handle_nans` treatment of tuple inputs

- src/hyrax/hyrax_default_config.toml
- src/hyrax/vector_dbs/chromadb_impl.py
- tests/hyrax/test_chromadb_impl.py
Adding configuration for shard size and warning for large vectors to chromadb_impl.
The user now has easier control over the shard size of the chromadb vector database. Additionally, a warning is emitted if the user is trying to insert vectors with >= 10k elements. And the 10k value is configurable in the config as well so they can easily turn off the warnings by setting this to false.
> Adding chromadb shard size and vector size configs

- src/hyrax/data_sets/fits_image_dataset.py
As you can see below, `FitsImageDataSet` has 5 objects, but it would say that it only processed 4.
The logging would print the {index} amount of objects, which start from 0 and is always 1 off from the true number of objects processed. Now it is {index+1}.
> Fixed logging for fits_image_dataset

- src/hyrax/3d_viz/save_umap_to_json.py
We skip over multidimensional columns as this leads to complications while converting to Pandas
> Skipping over multi-dimensional columns in 3D Visualization 

- src/hyrax/verbs/visualize.py
The run method of visualize was taking the `inference_dir` value directly from the config (it defaults to `False`) and passing that to instantiate the InferenceDataset. 
InferenceDataset expects a Path or str (or None) as the data types for `result_dir`. 
The change here will set `input_dir` to `None` if it is `false` in the config.
> Read inference_dir as `None` if it's `false` in the config

- docs/configuration.rst
- docs/pre_executed/train_model.ipynb
- src/hyrax/hyrax_default_config.toml
- src/hyrax/model_exporters.py
- src/hyrax/verbs/infer.py
- src/hyrax/verbs/train.py
- tests/hyrax/test_config_utils.py
- tests/hyrax/test_data/test_default_config.toml
- tests/hyrax/test_data/test_user_config.toml
Updating the `[train]` configuration file key name from `weights_filepath` to `weights_filename`.
Since the config parameter is actually used as a file name and not a path, this naming is more correct. There is also an `[infer][model_weights_file]` but that one is actually a path, not a file name. Considered changing that to `model_weights_filepath` but taking small steps here.
> Changing `weights_filepath` to `weights_filename`

- benchmarks/vector_db_benchmarks.py
- src/hyrax/data_sets/random/hyrax_random_dataset.py
- src/hyrax/hyrax_default_config.toml
- src/hyrax/models/hyrax_cnn.py
- src/hyrax/vector_dbs/chromadb_impl.py
- src/hyrax/vector_dbs/qdrantdb_impl.py
- src/hyrax/verbs/umap.py
- tests/hyrax/conftest.py
- tests/hyrax/test_chromadb_impl.py
- tests/hyrax/test_nan.py
- tests/hyrax/test_qdrant_impl.py
- tests/hyrax/test_save_to_database.py
- tests/hyrax/test_umap.py
We added a couple of configuration settings where we wanted the table name to include `.`s, which requires the use of double quotes, as in `["torch.optim.Adam"]`. Which is then accessed as `h.config["torch.optim.Adam"]`
However, we started using this incorrectly when we wanted a subtable, as in `["vector_db.chromadb"]` and then access it as `h.config["vector_db.chromadb"]`, when what we really want is `h.config["vector_db"]["chromadb"]`.
This PR cleans up the places where we incorrectly used the double quotes when creating subtables in the config files, as well as the assorted places in the code where we utilize the config values.
> Removes references to "table.sub_table" configuration settings when inappropriate

- src/hyrax/hyrax_default_config.toml
Added default value for `primary_id_field` that corresponds to the default dataset, `HyraxCifarDataset`.
At this time, inferece requires a `object_id` field in order to write out data, we need to provide a `primary_id_field` for HyraxQL to be able to provide the object_id to the InferenceDatasetWriter.
> Added default value for `primary_id_field` in .toml file

- src/hyrax/data_sets/data_provider.py
- src/hyrax/data_sets/data_set_registry.py
- src/hyrax/models/model_registry.py
- src/hyrax/plugin_utils.py
- src/hyrax/pytorch_ignite.py
- tests/hyrax/conftest.py
- tests/hyrax/test_data_provider.py
- tests/hyrax/test_plugin_utils.py
- tests/hyrax/test_pytorch_ignite.py
This should automatically load any dataset classes that are requested as libpaths. We were already doing this for models, but for some reason, we weren't doing this for dataset classes. 
Also removed `DataProvider.validate_request`.
Updated unit tests.
> Use of `fetch_dataset_class` instead of accessing DATA_SET_REGISTRY
