src/fibad/fibad_default_config.toml
src/fibad/plugin_utils.py
tests/fibad/test_plugin_utils.py

After a botched attempt to rebase from main, I've reimplemented the work from PR #67. This does the same work. FWIW, required changes will be ported over to the only external package, kbmod-ml.

Initial commit to consolidate name and external_cls.

---

.gitignore
src/fibad/config_utils.py
src/fibad/data_loaders/hsc_data_loader.py
src/fibad/fibad_default_config.toml
src/fibad/models/example_autoencoder.py
src/fibad/models/example_cnn_classifier.py
src/fibad/models/model_registry.py
src/fibad/predict.py
src/fibad/pytorch_ignite.py
src/fibad/train.py

- Predict basically works
- Most Pytorch ignite stuff has been factored out
- The results directory also basically works
- Predict is not yet outputting its results

Predict and Output scaffolding

---

src/fibad/fibad_default_config.toml
src/fibad/pytorch_ignite.py
src/fibad/train.py

This is the beginning of implementing checkpointing for training models. 
Need to pass in the config dictionary so that we can specify were to place the checkpoints, and read in a given checkpoint if the user chooses to do so. 
Also need to implement the ability to create a checkpoint at the "last best <metric>" value.

Implement checkpointing during training

---

src/fibad/fibad_default_config.toml

Fixing a couple of bugs in the default configuration file. 
The bugs were in the commented-out options/explanations being provided to users.

Quick Bug Fixes in fibad_default_config.toml

---

src/fibad/data_sets/hsc_data_set.py
tests/fibad/test_hsc_dataset.py

Altered logic for determining splits when partial information is provided among test, train, validate.
Added additional tests to cover missing permutations of test, train, validate being provided by the config system.

Hsc data set updates

---

src/fibad/data_sets/hsc_data_set.py
src/fibad/fibad_default_config.toml
tests/fibad/test_hsc_dataset.py

I added a config variable that controls whether images are cached or not during loading. 
This is meant to be a (temporary) fix till we invest time in implementing more elegant caching routines / distributed data loading etc. 
Feel free to push code directly if you spot something inefficient.

User Controlled Caching

---

.copier-answers.yml
.github/ISSUE_TEMPLATE/README.md
.github/workflows/README.md
.pre-commit-config.yaml
docs/conf.py
pyproject.toml
src/fibad/config_utils.py
src/fibad/data_sets/data_set_registry.py
src/fibad/data_sets/example_cifar_data_set.py
src/fibad/data_sets/hsc_data_set.py
src/fibad/download.py
src/fibad/downloadCutout/downloadCutout.py
src/fibad/download_stats.py
src/fibad/fibad.py
src/fibad/fibad_default_config.toml
src/fibad/infer.py
src/fibad/models/example_autoencoder.py
src/fibad/models/model_registry.py
src/fibad/plugin_utils.py
src/fibad/pytorch_ignite.py
tests/fibad/test_hsc_dataset.py

* Added mypy type checking to the codebase
* Fixed all type checking errors (clean `mypy .`)
* Fixed a couple of dataset split issues while testing download and train paths on new code and small datasets.
* Updated python project template to latest version, adding CI and pre-commit type checking

Type checking

---

docs/notebooks/train_model.ipynb

This PR fixes errors in the instructions for running tensorboard on a remote machine.

Fixing tensorboard instructions for running on a remote server

---

src/fibad/config_utils.py
src/fibad/data_sets/hsc_data_set.py
tests/fibad/test_config_utils.py

Remove config.get(...) call, replace this with a slightly less cool, if/else.

Remove config.get, use in line if/else for "rebuild_manifest".

---

pyproject.toml
src/fibad/data_sets/__init__.py
src/fibad/models/model_registry.py

Attempting to introduce enough typing in module_registry that mypy in pre-commit github actions will pass.

Fix github pre-commit mypy and import checks

---

docs/pre_executed/mpr_demo.html
docs/pre_executed/mpr_demo.ipynb
docs/pre_executed/mpr_demo_plotting.py
src/fibad/data_sets/inference_dataset.py

Just adding a UMAP section and plot. Also added a space in one of the info logs.

Adding a UMAP section to the notebook demo.

---

src/fibad/fibad_default_config.toml
src/fibad/models/__init__.py
src/fibad/models/hsc_dcae.py
src/fibad/models/hsc_dcae_v2.py

Hsc models

---

docs/configuration.rst
docs/data_set_splits.rst
docs/external_libraries.rst
docs/model_evaluation.rst
docs/notebooks.rst
docs/pre_executed/custom_dataset.ipynb
example_notebooks/GettingStartedDownloader.ipynb
src/hyrax/data_sets/data_set_registry.py
src/hyrax/data_sets/inference_dataset.py
src/hyrax/infer.py
src/hyrax/verbs/lookup.py
src/hyrax/verbs/umap.py
src/hyrax/verbs/visualize.py

- Comprehensive notebook showing how to build a custom dataset class
- Misc fixes to infer, umap, inference_dataset to codify the notion that dataset IDs may be any opaque type representable within a numpy array, rather than only values coercable to int64
- Documentation updates to Dataset covering recent changes to splits and overall dataset parent class interface.

Getting started with Hyrax Datasets notebook

---

src/hyrax/data_sets/hsc_data_set.py

Closes https://github.com/lincc-frameworks/hyrax/issues/286
Background:
`metadata = filter_catalog_table_dedup.loc["object_id", sorted_object_ids]`
in https://github.com/lincc-frameworks/hyrax/blob/main/src/hyrax/infer.py used to take about 10 hours for 10 million objects.
This PR replaces the `.loc` based indexing with a quicker dictionary-based lookup approach. This change preserves the ordering of object_ids while reducing run-time by 50X. 
Also adds a couple of debug-level logs in order to catch future issues in the metadata preparation step.

Slow Metadata Creation Fix

---

.github/workflows/smoke-test.yml
.github/workflows/testing-and-coverage.yml
.pre-commit-config.yaml
pyproject.toml
src/hyrax/data_sets/__init__.py
src/hyrax/data_sets/fits_image_dataset.py
src/hyrax/data_sets/hsc_data_set.py
src/hyrax/vector_dbs/chromadb_impl.py
src/hyrax/vector_dbs/vector_db_factory.py
src/hyrax/vector_dbs/vector_db_interface.py
tests/hyrax/test_e2e.py
tests/hyrax/test_hsc_dataset.py

- HSCDataset basically works, tests pass and `hyrax train` on HSC1000 works
- FitsImageDataSet has not been tested at all.
- rebuild_manifest has not been tested at all.
- Added end-to-end tests of FitsImageDataSet, HSCDataSet, and HyraxCifarDataSet.
- New Tests are enabled in CI and disabled in pre-commit
- Fixed some bugs in FitsImageDataSet
- Added warning/error text

Extracting FitsImageDataSet from HSCDataSet

---

README_RSP.md
src/hyrax/data_sets/__init__.py
src/hyrax/data_sets/lsst_dataset.py

This is so you can -- with a source install of hyrax on an RSP -- commit code to LSSTDataset and test it.

First version of LSSTDataset

---

src/hyrax/pytorch_ignite.py

this print snuck into my workflow :p
removed print statement

remove debug print statement

---

.gitignore

Updating gitignore to include json files (used by 3d visualization tool)

Addting json to gitignore

---

src/hyrax/data_sets/lsst_dataset.py

**TL;DR: We trust the lsst pipeline to give us the best patch and error when bounds of that patch are violated by config.**
The problem here is we need to make a cutout of a deep coadd based on the ra/dec of a source, and an arbitrary semi-height/semi-width in angular space. It is possible for the ra/dec and sh/sw extent to specify a box that is arbitrarily close and/or overlapping of any patch or tract boundary. We need to figure out generally correct behavior that will not be surprising to most scientists.
Because each patch's pixels don't line up with each other in patch overlap regions (thanks spherical geometry!), assembling a single cutout with pixels from multiple patch images requires us to reproject and somehow add pixels in some new projection space in order that the cutout …

Patch boundary handling in LSSTDataset

---

.pre-commit-config.yaml
benchmarks/benchmarks.py
src/hyrax/data_sets/data_set_registry.py
src/hyrax/data_sets/fits_image_dataset.py
src/hyrax/data_sets/hsc_data_set.py
src/hyrax/data_sets/hyrax_cifar_data_set.py
src/hyrax/data_sets/inference_dataset.py
src/hyrax/verbs/infer.py
src/hyrax/verbs/visualize.py

- Many top of file imports moved to functions
- Some type annotations removed
- Added benchmark test to measure our import time.

Reducing import time from ~2.7s to ~0.6s

---

tests/hyrax/conftest.py
tests/hyrax/test_chromadb_impl.py
tests/hyrax/test_infer.py
tests/hyrax/test_vdb_index.py

Moved some of the nice test fixtures out of test_infer into conftest for reuse.
Added test_vdb_index.
More validation of ids/values in test_chromadb_impl.

Adding tests for `index` verb

---

.pre-commit-config.yaml
src/hyrax/data_sets/fits_image_dataset.py

Just cleaning up something ugly
Before:
After:

Fixup to docs formatting

---

src/hyrax/3d_viz/image-viewer.js
src/hyrax/verbs/visualize.py

- Implements a lognorm-_ish_ scaling in both 2D and 3D visualization tools to ensure faint features also pop out in our display frames
- Also gets rid of some debug-level code in the 2D visualization tool. Keeps some stuff which might be helpful later in case needed. 
- Updates the logic in 2D visualization so that we always attempt to display the UMAP irrespective of the value of the ``return_verb" argument

Visualisation Scaling & Cleaning

---

benchmarks/benchmarks.py
benchmarks/vector_db_benchmarks.py

Fixed a benchmark for `index` timing that I should have updated when index was renamed to `save_to_database`. Added a timing benchmark for `database_connection`.

More benchmarks for vector db - search

---

src/hyrax/pytorch_ignite.py

Currently the create_trainer and create_validator functions expect that the `train_step` method in the model class will return a "loss" value. 
The user should be free to return and track any metrics produced in the `train_step` method. This change enables that. 
As long as the returned value from `train_step` is a dictionary, the metrics will be recorded in TensorBoard and MLFlow. 
For reference the return dict should look something like this: 
```
return {
'metric_0': metric_0_value,
...,
'metric_n': metric_n_value,
}
```

Update pytorch_ignite.py to track any metric returned by `train_step`

---

src/hyrax/pytorch_ignite.py

I was too trigger happy with the last PR and merged without fixing the pre-commit failure. This PR fixes the error.

Fixing pre-commit failure

---

src/hyrax/verbs/save_to_database.py

Mini-PR: Logs the location where the vectordb is being created.

Logs the VectorDB Location 

---

src/hyrax/3d_viz/image-viewer.js
src/hyrax/3d_viz/index.html
src/hyrax/3d_viz/script.js
src/hyrax/3d_viz/start_3d_viz_server.py
src/hyrax/3d_viz/styles.css

The 3D Visualization module can now 
- Read in PyTorch images in addition to FITS images
- Gives the user more flexibility in choosing colormaps

Making 3D Visualisation More Flexible 

---

src/hyrax/hyrax_default_config.toml
src/hyrax/models/__init__.py
src/hyrax/models/simclr.py

- Added `SimCLR` model to the Hyrax built-in model registry.
- This version of `SimCLR` is very basic, but it is functional. The feature extractor is based on a default `resnet18`. The feature extractor can be changed to improve the model (e.g., in a future PR).
- `NTXentLoss` is used as the default loss function of the model. The implementation is based on [Chen, 2020](https://arxiv.org/abs/2002.05709)

Add basic SimCLR model

---

benchmarks/data_request_benchmarks.py

This benchmark configures a HyraxRandomDataset with a (3, 64, 64) "image" with a total of 4096 samples. It then randomly picks 128 indexes and records timing metrics for retrieving all 128 samples by index. 
We can use this same metric to see if there are substantial differences when we implement the HyraxQL approach that will introduce the DataProvider class in between the user and the dataset.

Implement simple benchmark to request data from dataset

---

benchmarks/vector_db_benchmarks.py
src/hyrax/vector_dbs/qdrantdb_impl.py
tests/hyrax/test_qdrant_impl.py

Found the bug in the qdrant benchmark tests that also revealed a bug in the qdrant impl code. Fixed them both and updated unit tests.

Fix benchmark bug and qdrant vector db implementation bug
